In [ ]:
import numpy as np


In [ ]:
arr = np.arange(100000) #Creating vectors with a seq

In [ ]:
%%time
arr1 = 3*arr

CPU times: user 460 µs, sys: 1.08 ms, total: 1.54 ms
Wall time: 3.48 ms


In [ ]:
lst = list(range(1000))
arr = np.array(lst)

In [ ]:
print(arr)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [ ]:
first = arr[0]
last = arr[999]
print(first,last)

0 999


In [ ]:
arr[999] = 1000
first = arr[0]
last = arr[999]
print(first,last,arr[-1])

0 1000 1000


In [ ]:
print(np.arange(17,23,0.5))

[17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5 22.  22.5]


In [ ]:
##Basic Operations
arr1 = np.arange(1,6)
arr2 = np.arange(6,11)
print(arr1+arr2)
list1 = [1,2]
list2 = [3,4]
print(list1+list2)
print(arr1-arr2)
print(arr1*arr2)
print(np.around(arr1/arr2,2))
print(arr1**arr2)

[ 7  9 11 13 15]
[1, 2, 3, 4]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.17 0.29 0.38 0.44 0.5 ]
[      1     128    6561  262144 9765625]


In [ ]:
#Numpy Datatypes
arr = np.arange(1,6)
arr.dtype
arr1 = np.array([1,2,3,9],dtype=np.int8)
print(arr1.dtype)
print(arr.size)
print(arr.nbytes)
print(arr1.nbytes)

int8
5
40
4


In [ ]:
##Slicing
arr = np.arange(1,6)
print(arr[3:])
print(arr[:3])
print(arr[2:4])
print(arr[2:-2]) #Always end index as exclusive
print(arr[1:5:2])#Third is for step value
print(arr[::-1])#Reverse

[4 5]
[1 2 3]
[3 4]
[3]
[2 4]
[5 4 3 2 1]


In [ ]:
#Sorting
arr = np.array([5,6,2,8,2])
print(arr.sort())
print(arr)
arr = np.array([5,6,2,8,2])
print(np.sort(arr))
print(arr)
print(np.sort(arr,kind='heapsort'))

None
[2 2 5 6 8]
[2 2 5 6 8]
[5 6 2 8 2]
[2 2 5 6 8]


In [ ]:
#Copy Vs Views
#Some Operations/functions in numpy creates new array but some does inplace
arr = np.arange(1,6)
arr1 = arr[::-1]
arr1[0]=200
print(arr) # changes old array too - so Slicing don't create new array
print(arr1)
arr = np.arange(1,6)
arr1 = np.abs(arr)
arr1[0] = 200
print(arr) #np.abs() Doesn't change old array
print(arr1)

[  1   2   3   4 200]
[200   4   3   2   1]
[1 2 3 4 5]
[200   2   3   4   5]


In [ ]:
#Aggregate Functions
arr = np.arange(1,6)
print(np.sum(arr))

print(np.mean(arr))
print(np.prod(arr))
print(np.max(arr),np.min(arr)) #Gives min/max value
print(np.argmax(arr),np.argmin(arr)) #Gives index of min/max value

15
3.0
120
5 1
4 0
