In [1]:
import numpy as np

In [2]:
ls = [[1,2,3],[4,5,6]]
arr = np.array(ls)

In [3]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [4]:
arr.tolist()

[[1, 2, 3], [4, 5, 6]]

In [6]:
print(arr[1][1])

5


In [7]:
print(arr[1,1])

5


In [8]:
arr[1,1] = 100
print(arr)

[[  1   2   3]
 [  4 100   6]]


In [9]:
arr[:,2] #Gives back an 1D array

array([3, 6])